name: bankruptcy-prediction
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.0
  - pandas=2.0.3
  - numpy=1.26.4
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - seaborn=0.13.2
  - pip
  - pip:
    - xgboost==2.0.3
    - shap==0.45.1
    - tabulate==0.9.0
    - imbalanced-learn==0.11.0

